name: Cache Bazel Output
description: Caches Bazel output directories

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ${{ runner.os == 'Linux' && '~/.cache/bazel' || '/private/var/tmp/_bazel_runner/' }}
        key: bazel-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          bazel-${{ runner.os }}-
