name: Cache Bazel Output
description: Caches Bazel output directories

runs:
  using: "composite"
  steps:
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - uses: actions/cache@v3
      with:
        path: ${{ runner.os == 'Linux' && '~/.cache/bazel' || '/private/var/tmp/' }}
        key: bazel-output # N.B. Caches are not shared between OSs, so using the same key is fine
