name: Cache Bazel Output
description: Caches Bazel output directories

runs:
  using: "composite"
  steps:
    # Get the user name
    - name: "Get the user name"
      id: get_user_name
      run: |
        echo "::set-output name=user_name::$(id -un)"
    - uses: actions/cache@v3
      with:
        path: ${{ runner.os == 'Linux' && '~/.cache/bazel' || env.user_name }}
        key: bazel-output # N.B. Caches are not shared between OSs, so using the same key is fine
