name: Cache Bazel Output
description: Caches Bazel output directories

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      env:
        macos_path: "/private/var/tmp/$USER"
      with:
        path: ${{ runner.os == 'Linux' && '~/.cache/bazel' || env.macos_path }}
        key: bazel-output # N.B. Caches are not shared between OSs, so using the same key is fine
