name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: "Build the library"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk build --compilation_mode=fastbuild //...

    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: "Report test coverage"
              run: |
                  tools/bazelisk coverage --combined_report=lcov --instrument_test_targets //...

            - name: "Submit report to Coveralls"
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: ${{ github.workspace }}/bazel-out/_coverage/_coverage_report.dat

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: "Check clang-format version"
              run: |
                  clang-format --version

            - name: "Check code formatting"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test --compilation_mode=fastbuild --config lint //...

    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: "Check unit tests"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test //...

    ci_success:
        name: "CI success"
        runs-on: ubuntu-latest
        needs: [build, coverage, lint, test]
        steps:
            - run: echo "CI workflow completed successfully"
